export const dataCards = [
    {
        id: 1, 
        image_project: './img/sunnyside.png',
        link_project: 'https://calcagnoloic.github.io/Sunnyside-agency-react/', 
        title: 'Sunnyside agency',
        message: "Réalisation d'une landing page avec React et TailwindCSS en suivant les instructions d'un challenge Frontend Mentor.",
        lang1: './img/react.png', 
        lang2: '/img/tailwind.png',
        logo_github: './img/github.png',
        open_view: './img/newtab.png',
        link_github: 'https://github.com/CalcagnoLoic/Sunnyside-agency-react/tree/main',
    }, 
    {
        id: 2, 
        image_project: './img/hangman.png',
        link_project: 'https://calcagnoloic.github.io/Hangman-app/', 
        title: 'Hangman',
        message: "Réalisation d'un jeu 2D durant ma formation à BeCode. Ce pendu a été réalisé en Vanilla Javascript.",
        lang1: './img/html.png', 
        lang2: '/img/sass.png',
        lang3: './img/js.png',
        logo_github: './img/github.png',
        open_view: './img/newtab.png',
        link_github: 'https://github.com/CalcagnoLoic/Hangman-app',
    }, 
    {
        id: 3, 
        image_project: './img/movieflix.png',
        link_project: '/', 
        title: 'MovieFlix',
        message: "Projet fullstack personnel. Réalisation d'un petit site permettant de voir 20 films par genres. Les informations des différents films proviennent de l'API TMDb.",
        lang1: './img/html.png', 
        lang2: '/img/sass.png',
        lang3: './img/js.png', 
        lang4: '/img/mysql.png',
        lang5: '/img/php.png',
        logo_github: './img/github.png',
        open_view: './img/newtab.png',
        link_github: 'https://github.com/CalcagnoLoic/MovieFlix',
    }
]